### ISSUE TITLE
Did you consider hosting this plugin under the jenkinsci org?

### ISSUE THREAD

**Issue by batmat** [jwmach1/parameterized-scheduler#1]
Hi,

Found this plugin and we may have a use case for it. In this case, would you be OK to have it hosted under the jenkins official organization?

If you wish, I can help you through the process.

As I saw the last commit was 2 years ago, I'd understand if you don't plan to keep working/maintaining it. In this case, would you mind if I fork it myself and push it under the Jenkins org? In this case, I'd handle its maintenance.

Thanks a lot for your answer!

**Comment by batmat** [comment]
ping @jwmach1 in case you don't automatically receive notifications on that repo.

**Comment by jwmach1** [comment]
I did consider it. And I was going to set it up, but before I got it done work pulled me in another direction. Please, by all means, fork and get it registered in the jenkins plugin site.

**Comment by batmat** [comment]
OK, thanks. Do you want to be a maintainer or do you think you won't have time?

I'm personnally planning to work on it anyway. We could be co-maintainer if you wish. 

If you don't think you'll be able to spend time on it, just tell me and I'll go ahead without bothering you.

Thanks

**Comment by jwmach1** [comment]
Since I've left it dormant, and don't expect to start maintaining, it might
be more appropriate to add you as a contributor.

**Comment by batmat** [comment]
OK, thanks. I'll put myself only if I finally go this way. Don't hesitate to ask if you want to work on it in the future.
Thanks

**Comment by batmat** [comment]
for the record, the plugin has been forked under https://github.com/jenkinsci/parameterized-scheduler-plugin

Cheers
