### ISSUE TITLE
Global Config is a hello world script

### ISSUE THREAD

**Issue by mhijazi1** [jwmach1/parameterized-scheduler#11]
The Global config for this plugin uses a boiler plate hello world config. 
[See here](https://github.com/jwmach1/parameterized-scheduler/blob/master/src/main/resources/org/jenkinsci/plugins/parameterizedschedular/ParameterizedTimerTrigger/global.jelly#L16)

![Viva La France](https://i.imgur.com/5Nvwwyh.png)
I'm happy to remove this (Just wasn't sure what the implications of just deleting it would be) or update the config to not talk to me about French and be something a bit more related.

**Comment by jwmach1** [comment]
I put a note at the top of the README, pointing out that you likely want to take a look at the fork which is the plugin registered in the Jenkins registry. https://github.com/jenkinsci/parameterized-scheduler-plugin.
